#!/usr/bin/env bash
# Install and setup HAProxy as a load balancer

sudo apt-get update
sudo apt-get -y install haproxy

# Configure haproxy
cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
listen load_balancer
        bind :80
        mode http
        option httpclose
        option forwardfor
        balance roundrobin
        server 514012-web-01 54.236.51.196:80 check
        server 514012-web-02 35.153.83.101:80 check
EOF

# Restart haproxy using init script
sudo service haproxy restart
